name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  job1: 
    name: Build and test React-client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build React-tests image
      run: docker build -t astralox/react-tests -f ./client/Dockerfile.dev ./client
    - name: Run React-tests
      run: docker run -e CI=true astralox/react-tests npm test
    
  job2:
    name: Build production client image
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build production client image
      run: docker build -t astralox/multi-client ./client
    - name: Login to docker hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_ID }} --password-stdin
    - name: Push multi-client to hub.docker.com
      run: docker push astralox/multi-client

  job3:
    name: Build production nginx image
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build production nginx image
      run: docker build -t astralox/multi-nginx ./nginx
    - name: Login to docker hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_ID }} --password-stdin
    - name: Push multi-nginx to hub.docker.com
      run: docker push astralox/multi-nginx

  job4:
    name: Build production server image
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build production server image
      run: docker build -t atralox/multi-server ./server
    - name: Login to docker hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_ID }} --password-stdin
    - name: Push multi-server to hub.docker.com
      run: docker push astralox/multi-server

  job5:
    name: Build production worker image
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build production worker image
      run: docker build -t astralox/multi-worker ./worker
    - name: Login to docker hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_ID }} --password-stdin
    - name: Push multi-worker to hub.docker.com
      run: docker push astralox/multi-worker
